# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module Grid::ChunkyPNG::Color::BLACK; end
module Grid::ChunkyPNG::Color::WHITE; end
module Grid::ChunkyPNG::Image; end
module YARD::Logger; end
